# Generated by Django 4.2.5 on 2023-09-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='description',
        ),
    ]
