# Generated by Django 4.2.5 on 2023-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_remove_rides_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='id',
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_desc',
            field=models.TextField(default='smeraaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_img',
            field=models.ImageField(default='imagee', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='b1_color',
            field=models.CharField(default='fffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='b2_color',
            field=models.CharField(default='eeeee', max_length=7),
            preserve_default=False,
        ),
    ]
