# Generated by Django 4.2.5 on 2023-09-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0004_remove_rides_adv_id_rides_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='id',
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
