# Generated by Django 4.2.5 on 2023-09-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0006_remove_rides_adv_id_rides_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='adv_desc',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='adv_img',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='b1_color',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='b2_color',
        ),
    ]
