# Generated by Django 4.2.5 on 2023-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0007_remove_rides_adv_desc_remove_rides_adv_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='adv_desc',
            field=models.TextField(default='skyyyyy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_img',
            field=models.ImageField(default='hhhhhh', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='b1_color',
            field=models.CharField(default='gggggg', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='b2_color',
            field=models.CharField(default='fffff', max_length=7),
            preserve_default=False,
        ),
    ]
