# Generated by Django 4.2.5 on 2023-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0008_rides_adv_desc_rides_adv_img_rides_b1_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='id',
        ),
        migrations.AddField(
            model_name='rides',
            name='adv_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
