# Generated by Django 4.2.5 on 2023-09-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0009_remove_rides_id_rides_adv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='b1_color',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='rides',
            name='b2_color',
            field=models.CharField(max_length=9),
        ),
    ]
