# Generated by Django 4.2.5 on 2023-09-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0010_alter_rides_b1_color_alter_rides_b2_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=120)),
                ('reg_age', models.IntegerField()),
                ('reg_weight', models.IntegerField()),
                ('reg_phno', models.IntegerField()),
                ('advent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advapp.rides')),
            ],
        ),
    ]
